Make sure using raw strings for the install_dir
Somehow this we are getting unicode strings in here.  I would say it's
either the caching layer converting providing unicode strings, or it's
been a problem all along, and we just discovered it.

Without this it causes the replacement operation to fail with:

  UnicodeDecodeError: 'ascii' codec can't decode byte 0x9a